import type { TypedFeedItem } from './types'

export const mockTypedFeedItems: TypedFeedItem[] = [
  {
    type: 'direct_sent',
    id: 'mock-direct-sent-unanswered',
    senderName: 'Maya',
    metadata: 'Maya sent this · Today',
    category: 'Food & Drink',
    question: 'Which fermented tea is often kept alive by a SCOBY?',
    personalMessage: 'This felt like your kind of kitchen lore.',
  },
  {
    type: 'friend_answered',
    id: 'mock-friend-answered-right',
    friendName: 'Noah',
    friendCorrect: true,
    metadata: 'Noah got this right · Yesterday',
    category: 'Science',
    question: 'What kind of celestial object is a magnetar?',
    answerSummary:
      'Noah recognized this one. See if you share the same common ground.',
  },
  {
    type: 'friend_added',
    id: 'mock-friend-added',
    friendName: 'Ari',
    metadata: 'Ari wrote a question · May 9',
    category: 'History',
    question: 'What treaty formally ended World War I for Germany?',
  },
  {
    type: 'friend_liked',
    id: 'mock-friend-liked',
    friendName: 'Sam',
    metadata: 'Sam liked this · May 8',
    category: 'Music',
    question: 'Which instrument family does the oboe belong to?',
  },
  {
    type: 'friend_liked',
    id: 'mock-friend-liked-collapsed',
    friendName: 'Sam',
    metadata: 'Sam and 2 friends liked this · May 8',
    category: 'Music',
    question: 'What jazz pianist wrote “Blue Monk”?',
    endorsementCount: 3,
    additionalEndorsers: [
      { userId: 'friend-lena', displayName: 'Lena' },
      { userId: 'friend-kai', displayName: 'Kai' },
    ],
  },
  {
    type: 'answered_by_you',
    id: 'mock-answered-by-you-correct',
    metadata: 'You answered · May 7',
    category: 'Sports',
    broadCategory: 'Sports',
    question: 'Which city hosted the 1992 Summer Olympics?',
    resultLabel: 'You answered',
    answerSummary: 'You both had it.',
    submittedAnswer: 'Barcelona',
    correctAnswer: 'Barcelona',
    isCorrect: true,
    awardedPoints: 5,
    masteryDelta: {
      previousTier: 'familiar',
      newTier: 'solid',
      tierChanged: true,
    },
  },
  {
    type: 'answered_by_you',
    id: 'mock-answered-by-you-wrong',
    metadata: 'You answered · May 7',
    category: 'Geography',
    question: 'Which capital city sits on the Tagus River?',
    resultLabel: 'Reviewed privately',
    answerSummary: 'Maya recognized this one. You might next time.',
    submittedAnswer: 'Madrid',
    correctAnswer: 'Lisbon',
    isCorrect: false,
    awardedPoints: 0,
  },
  {
    type: 'friend_added',
    id: 'mock-missing-suppressed-category',
    friendName: 'Rae',
    metadata: 'Rae wrote a question · May 6',
    category: 'General Knowledge',
    question: 'Which word means a word formed from initials?',
  },
  {
    type: 'direct_sent',
    id: 'mock-already-banked',
    senderName: 'Maya',
    metadata: 'Maya sent this · May 6',
    category: 'Literature',
    question: 'Who wrote Kindred?',
    isInBank: true,
  },
  {
    type: 'answered_by_you',
    id: 'mock-unverified-answered-note',
    metadata: 'You answered · May 5',
    category: 'Film',
    broadCategory: 'Film & Television',
    question: 'Which editor cut Raging Bull?',
    resultLabel: 'You answered',
    answerSummary: 'You answered this question.',
    submittedAnswer: 'Thelma Schoonmaker',
    correctAnswer: 'Thelma Schoonmaker',
    isCorrect: true,
    awardedPoints: 3,
    explanation: 'Explanation is pending verification by the question author.',
    unverifiedAnswer: true,
    masteryDelta: {
      previousTier: 'familiar',
      newTier: 'familiar',
      tierChanged: false,
    },
  },
]

export const feedCardPreviewFixtures = {
  directSentUnanswered: mockTypedFeedItems[0],
  friendAnsweredRight: mockTypedFeedItems[1],
  friendAddedWroteQuestion: mockTypedFeedItems[2],
  friendLikedShared: mockTypedFeedItems[3],
  friendLikedCollapsedMultiEndorsement: mockTypedFeedItems[4],
  answeredByYouCorrect: mockTypedFeedItems[5],
  answeredByYouWrong: mockTypedFeedItems[6],
  missingSuppressedCategory: mockTypedFeedItems[7],
  alreadyBankedItem: mockTypedFeedItems[8],
  unverifiedAnsweredExplanationNote: mockTypedFeedItems[9],
} satisfies Record<string, TypedFeedItem>
