-- B-LLM-PROVIDER-AB-SWITCH B3 — provider provenance stamping.
--
-- Records which provider produced each piece of LLM output, so the experiment is
-- measurable against the north-star (reaction rate on wrong answers) and other
-- signals. Three independent, nullable columns on three different landing rows —
-- deliberately NOT one shared column, because a question can be generated by one
-- provider and categorized by another, and grading is a separate event entirely:
--
--   * GeneratedQuestion.generated_by_provider — the provider that GENERATED the
--     machine-bank row (set at persist time in generate-questions.ts).
--   * Question.categorize_provider — the provider that CATEGORIZED an authored
--     question (set where categorizeQuestion's output lands).
--   * MASTERY_EVENTS.llm_provider — the provider that GRADED an answer, on the
--     per-answer event row (carries answer_state, so wrong answers — the
--     north-star — are covered). Null when the grade never hit an LLM (exact-match
--     fast-path or give-up) or when grading wasn't routed.
--
-- All three are nullable text with no default: historical rows stay null (no
-- backfill, by design) and only new output is stamped. Additive only — no
-- existing column/table is altered, and RLS is already enabled on all three
-- tables. Idempotent (ADD COLUMN IF NOT EXISTS); mirrored by defensive guards in
-- src/instrumentation.ts (precedent: 0085/0086) so a preview/production database
-- that records this migration without the columns present still gets them.
--
-- Rollback:
--   ALTER TABLE "GeneratedQuestion" DROP COLUMN IF EXISTS "generated_by_provider";
--   ALTER TABLE "Question" DROP COLUMN IF EXISTS "categorize_provider";
--   ALTER TABLE "MASTERY_EVENTS" DROP COLUMN IF EXISTS "llm_provider";
ALTER TABLE "GeneratedQuestion"
  ADD COLUMN IF NOT EXISTS "generated_by_provider" text;
--> statement-breakpoint
ALTER TABLE "Question"
  ADD COLUMN IF NOT EXISTS "categorize_provider" text;
--> statement-breakpoint
ALTER TABLE "MASTERY_EVENTS"
  ADD COLUMN IF NOT EXISTS "llm_provider" text;
