import type { FragmentationPair } from '@/server/db/queries/domain-fragmentation';

export type DomainFragmentationEmail = {
  subject: string;
  html: string;
  text: string;
};

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function pct(similarity: number): string {
  return `${Math.round(similarity * 100)}%`;
}

/**
 * Weekly "domains that may want merging" digest. Each pair is a judgment call the
 * automated reconcile deliberately left alone — the owner decides merge vs keep.
 * Pure render; the cron resolves the recipient and sends.
 */
export function buildDomainFragmentationEmailTemplate(
  pairs: FragmentationPair[],
): DomainFragmentationEmail {
  const subject =
    pairs.length === 0
      ? 'Domain review: nothing to look at this week'
      : `Domain review: ${pairs.length} cluster${pairs.length === 1 ? '' : 's'} to eyeball`;

  if (pairs.length === 0) {
    const text =
      'No near-duplicate domain clusters crossed the review threshold this week. Tier-1 prevention is holding.';
    return {
      subject,
      text,
      html: `<p>${escapeHtml(text)}</p>`,
    };
  }

  const intro =
    'These domain pairs look similar but were not auto-merged — each is a judgment call. ' +
    'If a pair is the same scope, reply and I’ll merge them; if they’re genuinely different ' +
    '(a specific work vs its genre, two siblings), leave them.';

  const textLines = pairs.map(
    (p, i) =>
      `${i + 1}. ${p.domainA} (${p.depthA}) ≈ ${p.domainB} (${p.depthB})  —  ${pct(p.similarity)} similar`,
  );
  const text = `${intro}\n\n${textLines.join('\n')}\n\n(Number in parentheses = how many questions are filed under that label.)`;

  const rows = pairs
    .map(
      (p) => `
      <tr>
        <td style="padding:6px 10px;border-bottom:1px solid #eee;">${escapeHtml(p.domainA)} <span style="color:#888;">(${p.depthA})</span></td>
        <td style="padding:6px 10px;border-bottom:1px solid #eee;color:#888;">&asymp;</td>
        <td style="padding:6px 10px;border-bottom:1px solid #eee;">${escapeHtml(p.domainB)} <span style="color:#888;">(${p.depthB})</span></td>
        <td style="padding:6px 10px;border-bottom:1px solid #eee;text-align:right;color:#555;">${pct(p.similarity)}</td>
      </tr>`,
    )
    .join('');

  const html = `
    <div style="font-family:system-ui,-apple-system,Segoe UI,sans-serif;max-width:640px;">
      <p>${escapeHtml(intro)}</p>
      <table style="border-collapse:collapse;width:100%;font-size:14px;">
        <thead>
          <tr style="text-align:left;color:#888;font-size:12px;">
            <th style="padding:6px 10px;">Domain A (depth)</th>
            <th style="padding:6px 10px;"></th>
            <th style="padding:6px 10px;">Domain B (depth)</th>
            <th style="padding:6px 10px;text-align:right;">Similarity</th>
          </tr>
        </thead>
        <tbody>${rows}</tbody>
      </table>
      <p style="color:#888;font-size:12px;">Depth = questions filed under that label. Generated by the weekly domain-fragmentation cron.</p>
    </div>`;

  return { subject, html, text };
}
